### ISSUE TITLE
Look over my outline and start discussing filling out the talk.

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/github_workshop#1]
I put in a quick outline on the wiki. Now just look it over and we can start thinking about the presentation? Also, would you prefer PowerPoint, Latex or something else for the slides?

**Comment by cdmo** [comment]
I made some edits and inline comments. Let me know your thoughts.

https://github.com/psu-libraries/github_workshop/wiki/Outline

**Comment by cdmo** [comment]
And, PowerPoint is my preference.

**Comment by olendorf** [comment]
Looks good. Edits and comments are spot on. I'll tidy it up a bit when I'm
off my phone.
