### ISSUE TITLE
Slides editing and planning

### ISSUE THREAD

**Issue by olendorf** [psu-libraries/github_workshop#2]
I uploaded some slides copy and pasted from a similar talk. Looking over our outline, its looking like we might want to focus on live demos rather than slides after sections 1 and 2 of the outline. I edited the outline a little. 

The slides look to be about 15 minutes of time give or take, so this gives us lots of time for demos if we want. 

Section 3 could conceivably be screen shots too. not sure which is btter.

**Comment by cdmo** [comment]
I think this is a good start. I wonder if the research-specific slides in the beginning are appropriate for the audience we're talking to. I feel like the slides 2-6 might be confusing to folks uninitiated in code versioning or git (or the problems of sharing research data/collaborating across institutions). Slides 7 and 8 might be too much too? I think it might make more sense to assume our audience knows about saving multiple versions of the same file as the best means for file versioning, so starting with that and comparing with versioning in general might be a better start? And then talk about git as a sophisticated (yet fairly simple) way to handle collaborative code versioning.

The rest of the slides look good to me, and I'm assuming like you mentioned that we'll probably just be live demo in between talking about git's features?

**Comment by olendorf** [comment]
The original talk was for essentially thes same audience, librarians with limited technical background. They aren't meant to be talked about super technical, more to touch on various problems they probably have run into already in their own work, or at least have observed. They can definitely be revised, though. 

The thing we really don't want to do is to introduce git / github without really giving them a good idea of how it can be used. They will just decide it doesn't help them then. It also really seemed to resonate with a lot of the audience at that talk when I did it this way.

**Comment by cdmo** [comment]
Okay, I probably made some bad assumptions there about the audience! Sorry! I hope I didn't overstep :fearful: 

So, I guess items 3 and 4 from the wiki will be live demo? That sounds good to me.

**Comment by olendorf** [comment]
Gosh no, didn't overstep at all. I just realized the you probably thinking
about the slides different than I was.

Yap, think 3 and 4 for demo. I don't mind giving the first part, then we
divvy up the rest?

**Comment by cdmo** [comment]
Yeah that sounds great! Thanks.
